# Generated by Django 4.2.20 on 2025-05-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especializacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioInscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actividades.responsablesala')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('horario', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('duracion', models.DurationField()),
                ('plazas_disponibles', models.IntegerField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.monitor')),
                ('sala_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_principales', to='actividades.sala')),
                ('salas_secundarias', models.ManyToManyField(blank=True, related_name='actividades_secundarias', to='actividades.sala')),
                ('usuarios', models.ManyToManyField(blank=True, to='actividades.usuarioinscrito')),
            ],
        ),
    ]
